development:
    :address: smtp.gmail.com
    :port: 587
    :authentication: plain
    :user_name: therainbowchronicle
    :password: troegenator
    :enable_starttls_auto: true
production:
    :address: smtp.sendgrid.net
    :port: 587
    :authentication: plain
    :user_name: rainbowchronicle
    :password: Lilteezy1
    :enable_starttls_auto: true
